export type GlossaryCategory = "signal" | "action" | "phase" | "reward" | "concept";

export interface GlossaryLevel {
  range: string;
  label: string;
  meaning: string;
  color: string;
}

export interface GlossaryEntry {
  term: string;
  category: GlossaryCategory;
  plain: string;
  detail: string;
  range?: string;
  levels?: GlossaryLevel[];
  seeAlso?: string[];
}

export const GLOSSARY: GlossaryEntry[] = [
  // ── Signals ─────────────────────────────────────────────────────────────────
  {
    term: "Kafka Lag",
    category: "signal",
    plain: "How far behind the message queue processor is. High lag = the system is overwhelmed.",
    detail: "Kafka is a message queue. Lag is the number of unprocessed messages piling up. In this simulation it represents system backlog — if it keeps growing, the env enters spike then cascade phase, and latency compounds badly.",
    range: "0 – 10,000 messages",
    levels: [
      { range: "0 – 1,000",   label: "Healthy",   meaning: "System is keeping up. Normal routing is fine.",               color: "#22c55e" },
      { range: "1,000 – 3,000", label: "Building", meaning: "Backlog growing. Consider Throttle routing.",                color: "#f59e0b" },
      { range: "3,000 – 4,000", label: "Warning",  meaning: "Latency compounding has started. Switch to CircuitBreaker.", color: "#f97316" },
      { range: "4,000+",       label: "CRASH",     meaning: "Crash threshold. Cascade phase active. -1.0 reward/step.",  color: "#ef4444" },
    ],
    seeAlso: ["System Entropy", "Cascade Phase", "CircuitBreaker"],
  },
  {
    term: "Risk Score",
    category: "signal",
    plain: "How suspicious this transaction looks. Higher = more likely to be fraud.",
    detail: "Generated by the simulation each step based on adversary behavior and transaction type. The agent's job is to match the right action (Approve/Reject/Challenge) to this score. Wrong match = reward penalty.",
    range: "0 – 100",
    levels: [
      { range: "0 – 30",  label: "Low Risk",      meaning: "Safe to Approve. SkipVerify is acceptable.",           color: "#22c55e" },
      { range: "30 – 60", label: "Moderate",       meaning: "Consider Challenge. FullVerify recommended.",          color: "#f59e0b" },
      { range: "60 – 80", label: "High Risk",      meaning: "Reject or Challenge. SkipVerify will penalise.",       color: "#f97316" },
      { range: "80+",     label: "CRITICAL",       meaning: "Must Reject. Approving here gives -0.3 per step.",     color: "#ef4444" },
    ],
    seeAlso: ["Adversary Threat Level", "Crypto Verify", "Risk Decision"],
  },
  {
    term: "Adversary Threat Level",
    category: "signal",
    plain: "How aggressively the simulated attacker is behaving. Goes up when the agent does well — the env fights back.",
    detail: "This is the AEPO multi-agent adversary. It uses a Q-table to escalate pressure on the agent when it's performing well. Higher threat = harder sim conditions, more volatility in risk_score, and faster kafka_lag growth.",
    range: "0 – 10",
    levels: [
      { range: "0 – 3",  label: "Dormant",     meaning: "Adversary not yet engaged. Easy conditions.",        color: "#22c55e" },
      { range: "3 – 5",  label: "Probing",     meaning: "Adversary testing agent. Risk scores more volatile.", color: "#f59e0b" },
      { range: "5 – 8",  label: "Escalating",  meaning: "Adversary actively challenging. Expect spikes.",     color: "#f97316" },
      { range: "8 – 10", label: "MAX THREAT",  meaning: "Full escalation. Curriculum level likely promoted.",  color: "#ef4444" },
    ],
    seeAlso: ["Curriculum Level", "Risk Score"],
  },
  {
    term: "System Entropy",
    category: "signal",
    plain: "How chaotic/unstable the system is. Above 70% it causes a latency spike in the very next step.",
    detail: "Entropy is a chaos index that accumulates from adversary actions and high kafka lag. Think of it as 'system stress'. When it crosses 70, the simulation fires a latency spike — api_latency jumps sharply, which compounds into P99.",
    range: "0 – 100",
    levels: [
      { range: "0 – 30",  label: "Stable",    meaning: "No instability. System operating normally.",               color: "#22c55e" },
      { range: "30 – 50", label: "Mild",       meaning: "Some background stress. Monitor but no action needed.",    color: "#94a3b8" },
      { range: "50 – 70", label: "Unstable",   meaning: "Stress building. Throttle routing helps bleed entropy.",  color: "#f59e0b" },
      { range: "70+",     label: "SPIKE ZONE", meaning: "Latency spike fires NEXT step. Act now.",                 color: "#ef4444" },
    ],
    seeAlso: ["API Latency", "Rolling P99", "Spike Phase"],
  },
  {
    term: "Rolling P99",
    category: "signal",
    plain: "The smoothed latency average the SLA is judged on. Stays high for a while after a spike — it doesn't recover instantly.",
    detail: "EMA formula: 0.8 × previous_p99 + 0.2 × current_api_latency. Because 80% weight is on the previous value, one big spike takes many steps to bleed out. This is what triggers the -1.0 SLA penalty per step.",
    range: "0 – 5,000 ms",
    levels: [
      { range: "0 – 400ms",   label: "Healthy",    meaning: "Comfortable SLA headroom. No penalty.",              color: "#22c55e" },
      { range: "400 – 700ms", label: "Caution",    meaning: "Approaching SLA. Avoid adding more latency.",        color: "#f59e0b" },
      { range: "700 – 800ms", label: "Critical",   meaning: "About to breach. Use Throttle routing immediately.", color: "#f97316" },
      { range: "800ms+",      label: "SLA BREACH", meaning: "-1.0 reward penalty every step until it drops.",     color: "#ef4444" },
    ],
    seeAlso: ["API Latency", "SLA Penalty", "System Entropy"],
  },
  {
    term: "API Latency",
    category: "signal",
    plain: "The raw latency for this one step. Spikes during high entropy. This feeds into the P99 average.",
    detail: "Instantaneous latency sampled each step. Influenced by system entropy, kafka lag, and adversary actions. A single high value here pushes P99 up slightly (20% weight in EMA). Sustained high values breach SLA.",
    range: "0 – 5,000 ms",
    levels: [
      { range: "0 – 400ms",  label: "Fast",     meaning: "Normal operating range.",                           color: "#22c55e" },
      { range: "400 – 800ms",label: "Slow",     meaning: "Elevated. Pushing P99 upward.",                     color: "#f59e0b" },
      { range: "800ms+",     label: "Very Slow",meaning: "Single spike. P99 will rise on next few steps.",    color: "#ef4444" },
    ],
    seeAlso: ["Rolling P99", "System Entropy"],
  },
  {
    term: "DB Connection Pool",
    category: "signal",
    plain: "How many database connections are in use. Above 80% the DB slows down and the retry policy matters.",
    detail: "Represents database saturation. When pool > 80%, the simulation applies retry overhead. Using ExpBackoff policy at this point actually adds a -0.10 penalty — better to use FailFast policy unless you specifically need retries.",
    range: "0 – 100%",
    levels: [
      { range: "0 – 50%",  label: "Plenty",   meaning: "DB healthy. No action needed.",                     color: "#22c55e" },
      { range: "50 – 65%", label: "Moderate", meaning: "Watch trend. Still safe.",                          color: "#94a3b8" },
      { range: "65 – 80%", label: "Busy",     meaning: "Approaching overhead trigger. Prefer FailFast.",    color: "#f59e0b" },
      { range: "80%+",     label: "Saturated",meaning: "Retry overhead active. ExpBackoff adds -0.10.",     color: "#ef4444" },
    ],
    seeAlso: ["DB Retry Policy"],
  },
  {
    term: "Bank Sim Status",
    category: "signal",
    plain: "A simulated status of the payment processing path. Not a real bank — purely a sim signal that changes which settlement strategy earns a bonus.",
    detail: "Three states: Healthy (0), Degraded (1), Unknown (2). When Degraded, using DeferredAsync settlement gives +0.05 reward. When Healthy, StandardSync is fine. No real bank API is called — this is entirely simulated.",
    range: "0=Healthy, 1=Degraded, 2=Unknown",
    levels: [
      { range: "0 – Healthy",  label: "Healthy",  meaning: "StandardSync settlement is optimal.",           color: "#22c55e" },
      { range: "1 – Degraded", label: "Degraded", meaning: "Switch to DeferredAsync for +0.05 bonus.",      color: "#f59e0b" },
      { range: "2 – Unknown",  label: "Unknown",  meaning: "Uncertain state. DeferredAsync is safer.",       color: "#94a3b8" },
    ],
    seeAlso: ["Settlement Policy"],
  },
  {
    term: "Merchant Tier",
    category: "signal",
    plain: "The type of merchant involved — Small business or Enterprise. Determines which App Priority earns a bonus.",
    detail: "Binary signal. Small (0) merchants earn a +0.02/step bonus when App Priority is Balanced. Enterprise (1) merchants earn the same bonus when App Priority is UPI. Matching tier to priority is a small but consistent reward.",
    range: "0=Small, 1=Enterprise",
    seeAlso: ["App Priority"],
  },
  {
    term: "Payment Channel",
    category: "signal",
    plain: "The type of payment being processed — person-to-person, person-to-merchant, or automated recurring.",
    detail: "P2P (0) = money sent between individuals. P2M (1) = payment to a merchant. AutoPay (2) = automated recurring charge. The channel affects which routing strategy is statistically more rewarded by the sim.",
    range: "0=P2P, 1=P2M, 2=AutoPay",
    seeAlso: ["Infra Routing"],
  },

  // ── Actions ──────────────────────────────────────────────────────────────────
  {
    term: "Risk Decision",
    category: "action",
    plain: "The agent's verdict on the transaction — approve it, reject it, or flag it for review.",
    detail: "The most impactful action dimension. Reward is maximised when the decision matches the risk_score: Approve low-risk, Reject/Challenge high-risk. Mismatch (approve when risk > 80, or reject when risk < 30) gives -0.3.",
    levels: [
      { range: "0 = Approve",    label: "Approve",    meaning: "Pass transaction. +0.8 if risk < 50. -0.3 if risk > 80.",   color: "#22c55e" },
      { range: "1 = Reject",     label: "Reject",     meaning: "Block transaction. +0.8 if risk > 60. -0.3 if risk < 30.", color: "#ef4444" },
      { range: "2 = Challenge",  label: "Challenge",  meaning: "Request extra verification. Safe mid-range option.",       color: "#f59e0b" },
    ],
    seeAlso: ["Risk Score", "Crypto Verify"],
  },
  {
    term: "Crypto Verify",
    category: "action",
    plain: "Whether to fully verify the cryptographic signature of the transaction or skip it to save time.",
    detail: "FullVerify (0) adds latency but is always safe. SkipVerify (1) is faster but incurs a -0.3 penalty if risk_score > 50. Skip only when you're confident the transaction is low-risk.",
    levels: [
      { range: "0 = FullVerify", label: "FullVerify", meaning: "Safe always. Adds slight latency.",                 color: "#22c55e" },
      { range: "1 = SkipVerify", label: "SkipVerify", meaning: "-0.3 if risk_score > 50. Fast but risky.",         color: "#f97316" },
    ],
    seeAlso: ["Risk Score", "Risk Decision"],
  },
  {
    term: "Infra Routing",
    category: "action",
    plain: "How aggressively to throttle the infrastructure to control Kafka lag and latency.",
    detail: "Normal = full throughput, no intervention. Throttle = gradually reduces kafka_lag and entropy. CircuitBreaker = fastest lag reduction but cuts throughput (small penalty). Use CircuitBreaker when kafka_lag > 3000.",
    levels: [
      { range: "0 = Normal",         label: "Normal",         meaning: "Full throughput. Best when kafka_lag < 2000.",             color: "#22c55e" },
      { range: "1 = Throttle",       label: "Throttle",       meaning: "Reduces lag slowly. Good for creeping entropy.",          color: "#f59e0b" },
      { range: "2 = CircuitBreaker", label: "CircuitBreaker", meaning: "Fast lag reduction. -0.05 throughput penalty.",           color: "#ef4444" },
    ],
    seeAlso: ["Kafka Lag", "System Entropy"],
  },
  {
    term: "DB Retry Policy",
    category: "action",
    plain: "What to do when a database call fails — give up immediately or retry with increasing delays.",
    detail: "FailFast (0) is the safe default and has no penalty. ExpBackoff (1) retries automatically but adds -0.10 to reward. Only beneficial if DB pool is consistently > 80% and you want to recover connections.",
    levels: [
      { range: "0 = FailFast",      label: "FailFast",     meaning: "No penalty. Default for most situations.",      color: "#22c55e" },
      { range: "1 = ExpBackoff",    label: "ExpBackoff",   meaning: "-0.10 penalty. Only use when DB pool > 80%.",   color: "#f59e0b" },
    ],
    seeAlso: ["DB Connection Pool"],
  },
  {
    term: "Settlement Policy",
    category: "action",
    plain: "Whether to settle the transaction immediately or queue it for later processing.",
    detail: "StandardSync (0) = immediate settlement, no bonus. DeferredAsync (1) = queue for batch settlement, gives +0.05 when bank sim status is Degraded. When bank sim is Healthy, StandardSync is equally good.",
    levels: [
      { range: "0 = StandardSync",    label: "Standard",  meaning: "Immediate. No penalty or bonus.",                  color: "#22c55e" },
      { range: "1 = DeferredAsync",   label: "Deferred",  meaning: "+0.05 when bank sim is Degraded.",                 color: "#3b82f6" },
    ],
    seeAlso: ["Bank Sim Status"],
  },
  {
    term: "App Priority",
    category: "action",
    plain: "Which payment rail to prioritise — UPI, credit, or balanced. Match to merchant tier for a small bonus.",
    detail: "Enterprise merchants (tier=1) earn +0.02/step when App Priority is UPI. Small merchants (tier=0) earn +0.02/step when App Priority is Balanced. Mismatching gives no bonus but no penalty either.",
    levels: [
      { range: "0 = UPI",      label: "UPI",       meaning: "+0.02 bonus when merchant is Enterprise.",  color: "#3b82f6" },
      { range: "1 = Credit",   label: "Credit",    meaning: "No specific bonus in current sim config.",   color: "#94a3b8" },
      { range: "2 = Balanced", label: "Balanced",  meaning: "+0.02 bonus when merchant is Small.",        color: "#22c55e" },
    ],
    seeAlso: ["Merchant Tier"],
  },

  // ── Phases ───────────────────────────────────────────────────────────────────
  {
    term: "Normal Phase",
    category: "phase",
    plain: "The sim is operating under standard conditions. Signals are stable, thresholds not breached.",
    detail: "Default env state. Risk scores are moderate, kafka lag is manageable, adversary is probing but not escalating. This is where most reward is earned — consistent Approve + FullVerify + Normal routing gives ~0.8/step.",
  },
  {
    term: "Spike Phase",
    category: "phase",
    plain: "A latency spike just fired because entropy crossed 70. API latency jumps sharply and P99 starts climbing.",
    detail: "Triggered when system_entropy > 70. The api_latency sim value spikes in the next step. P99 follows slowly due to EMA smoothing. Agent should switch to Throttle routing to bleed entropy and prevent cascade.",
    seeAlso: ["System Entropy", "Rolling P99", "Cascade Phase"],
  },
  {
    term: "Cascade Phase",
    category: "phase",
    plain: "Full system failure mode — Kafka lag crossed 4,000 AND adversary is at high escalation. Everything compounds.",
    detail: "The hardest phase. Kafka lag > 4,000 activates this. Latency is high, entropy is spiking, risk scores are volatile. The -1.0 SLA penalty fires every step. CircuitBreaker routing is the only way to reduce lag fast enough.",
    seeAlso: ["Kafka Lag", "Adversary Threat Level", "CircuitBreaker"],
  },

  // ── Reward concepts ──────────────────────────────────────────────────────────
  {
    term: "SLA Penalty",
    category: "reward",
    plain: "A -1.0 penalty applied every single step the Rolling P99 stays above 800ms.",
    detail: "SLA = Service Level Agreement. This simulation's SLA threshold is 800ms P99. Because P99 is EMA-smoothed, once you breach 800ms it takes many steps of low latency to recover. Each step above = -1.0. This is the biggest single reward killer.",
    seeAlso: ["Rolling P99", "API Latency"],
  },
  {
    term: "Fraud Reward",
    category: "reward",
    plain: "The main reward signal — earned when the agent's decision matches the transaction's actual risk level.",
    detail: "+0.8 for correct match (Approve low-risk, Reject/Challenge high-risk). -0.3 for mismatch. Matching correctly on every step at ~0.8 is the baseline good performance.",
    seeAlso: ["Risk Decision", "Risk Score"],
  },
  {
    term: "Adversary Penalty",
    category: "reward",
    plain: "A growing penalty as the adversary escalates. The harder the adversary pushes, the more each step costs.",
    detail: "Grows from 0 to -0.5 as adversary_threat_level rises from 0 to 10. The agent can't eliminate this penalty directly — it's a function of adversary state. Managing kafka_lag and entropy limits how fast the adversary escalates.",
    seeAlso: ["Adversary Threat Level"],
  },

  // ── Key concepts ─────────────────────────────────────────────────────────────
  {
    term: "Curriculum Level",
    category: "concept",
    plain: "The env's internal difficulty setting. Auto-promoted when the agent performs well — it gets harder to keep earning the same score.",
    detail: "Three levels: 0 (easy conditions), 1 (medium), 2 (hard). The env promotes level when the agent's recent mean reward exceeds a threshold. Higher levels mean more volatile signals, faster adversary escalation, and tighter SLA windows.",
    levels: [
      { range: "Level 0", label: "Easy",   meaning: "Low adversary, stable signals. ~0.8 avg reward typical.", color: "#22c55e" },
      { range: "Level 1", label: "Medium", meaning: "Moderate adversary, occasional spikes.",                   color: "#f59e0b" },
      { range: "Level 2", label: "Hard",   meaning: "Full adversary escalation, cascade events frequent.",      color: "#ef4444" },
    ],
    seeAlso: ["Adversary Threat Level", "Cascade Phase"],
  },
  {
    term: "EMA",
    category: "concept",
    plain: "Exponential Moving Average — a smoothing formula that weighs recent values more but never fully forgets old ones.",
    detail: "Formula: new_ema = 0.8 × old_ema + 0.2 × new_value. Used for Rolling P99. Consequence: a single latency spike only bumps P99 by 20%. But if latency stays high for many steps, P99 climbs steadily. Recovery after a breach is slow.",
    seeAlso: ["Rolling P99"],
  },
  {
    term: "Episode",
    category: "concept",
    plain: "One full run of the simulation from Reset to done=true. Typically 100 steps.",
    detail: "An episode starts with POST /reset and ends when POST /step returns done=true (usually after 100 steps). The score for the episode is total_reward ÷ steps. Compared against the task threshold to determine PASS/FAIL.",
    seeAlso: ["Curriculum Level"],
  },
  {
    term: "Q-Table",
    category: "concept",
    plain: "A lookup table the RL agent uses to decide the best action for each situation. Each cell = 'how good is this action in this situation?'",
    detail: "Q-learning is a reinforcement learning algorithm. The Q-table maps (state, action) → expected reward. During training, the agent updates these values from experience. The heatmap shows high-Q cells (red = preferred) vs low-Q cells (blue = avoid). Generated by running python train.py.",
    seeAlso: ["Curriculum Level", "Episode"],
  },
  {
    term: "CircuitBreaker",
    category: "concept",
    plain: "An engineering pattern that stops retrying a failing system to let it recover. Here it's the fastest way to reduce Kafka lag.",
    detail: "In real systems, a circuit breaker stops sending requests to an overloaded service. In AEPO, selecting CircuitBreaker as Infra Routing aggressively sheds kafka_lag at the cost of a small throughput penalty. Essential during cascade phase.",
    seeAlso: ["Kafka Lag", "Infra Routing", "Cascade Phase"],
  },
  {
    term: "P99 Latency",
    category: "concept",
    plain: "99th percentile latency — the worst response time experienced by 99% of requests. The SLA metric.",
    detail: "P99 means '99% of requests completed within this time'. If P99 = 800ms, only 1% of requests took longer. In AEPO the rolling_p99 field is an EMA approximation of this. The true P99 from a 20-step ring buffer is in info['true_p99'].",
    seeAlso: ["Rolling P99", "SLA Penalty"],
  },
];

export const CATEGORIES: { id: GlossaryCategory; label: string; color: string }[] = [
  { id: "signal",  label: "Signals",  color: "text-blue-400 bg-blue-500/10 border-blue-500/30" },
  { id: "action",  label: "Actions",  color: "text-green-400 bg-green-500/10 border-green-500/30" },
  { id: "phase",   label: "Phases",   color: "text-orange-400 bg-orange-500/10 border-orange-500/30" },
  { id: "reward",  label: "Rewards",  color: "text-yellow-400 bg-yellow-500/10 border-yellow-500/30" },
  { id: "concept", label: "Concepts", color: "text-purple-400 bg-purple-500/10 border-purple-500/30" },
];

export function searchGlossary(query: string): GlossaryEntry[] {
  if (!query.trim()) return GLOSSARY;
  const q = query.toLowerCase();
  return GLOSSARY.filter(
    (e) =>
      e.term.toLowerCase().includes(q) ||
      e.plain.toLowerCase().includes(q) ||
      e.detail.toLowerCase().includes(q) ||
      e.seeAlso?.some((s) => s.toLowerCase().includes(q))
  );
}
